#pragma once

#define BACNET_STATUS_BINARY_INPUT_COUNT 2U
#define BACNET_FIRMWARE_DATABASE_REVISION_OFFSET 3U
#define BACNET_ETHERNET_LINK_INPUT_INSTANCE 1001U
#define BACNET_IPV4_READY_INPUT_INSTANCE 1002U
#define BACNET_ETHERNET_LINK_INPUT_NAME "Status Ethernet Link"
#define BACNET_IPV4_READY_INPUT_NAME "Status IPv4 Assigned"

#define BACNET_CHIP_TEMPERATURE_VALUE_NAME "Chip Temperature"
#define BACNET_SYSTEM_UPTIME_VALUE_NAME "System Uptime"
#define BACNET_FREE_HEAP_VALUE_NAME "Free Heap"
#define BACNET_MINIMUM_FREE_HEAP_VALUE_NAME "Minimum Free Heap"
#define BACNET_ETHERNET_LINK_LOSSES_VALUE_NAME "Ethernet Link Losses"
#define BACNET_ETHERNET_RECONNECTS_VALUE_NAME "Ethernet Reconnects"
#define BACNET_RX_PACKETS_VALUE_NAME "BACnet RX Packets"
#define BACNET_PROTOCOL_ERRORS_VALUE_NAME "BACnet Protocol Errors"
#define BACNET_LAST_RESET_REASON_VALUE_NAME "Last Reset Reason"
#define BACNET_ACTIVE_COV_SUBSCRIPTIONS_VALUE_NAME "Active COV Subscriptions"
#define BACNET_BOOT_COUNT_VALUE_NAME "Boot Count"
#define BACNET_NETWORK_PORT_NAME "BACnet/IP Ethernet"
