#pragma once

#define BACNET_STATUS_BINARY_INPUT_COUNT 2U
#define BACNET_FIRMWARE_DATABASE_REVISION_OFFSET 3U
#define BACNET_ETHERNET_LINK_INPUT_INSTANCE 1001U
#define BACNET_IPV4_READY_INPUT_INSTANCE 1002U
#define BACNET_ETHERNET_LINK_INPUT_NAME "Status Ethernet Link"
#define BACNET_IPV4_READY_INPUT_NAME "Status IPv4 Assigned"
